### ISSUE TITLE
Marker events not working

### ISSUE THREAD

**Issue by Alberick** [ionic-team/ionic-native#1790]
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request

**Current behavior:**

I'm unable to listen to marker events on new ionic-native 4.0.0

**Expected behavior:**
'
I should be able to listen to marker events 

**Steps to reproduce:**

Install cordova plugin google maps v2
Install latests ionic-native 4.0.0
add a map
add a marker
add a event listener for the marker

**Related code:**

```
insert any relevant code here
```
                    let markerOpts: MarkerOptions = {
                        title: place.name,
                        position: markerPosition,
                        animation: 'DROP',
                    };

                    this.map.addMarker(markerOpts)
                        .then((marker: Marker) => {
                            marker.one(GoogleMapsEvent.MARKER_CLICK)
                                .then(data => console.log('event one', data));

                            marker.on(GoogleMapsEvent.INFO_OPEN)
                                .subscribe(data => console.log('event on', data));

                            marker.addListenerOnce(GoogleMapsEvent.MARKER_CLICK)
                                .then(data => console.log('event once data', data));

                            marker.addEventListener(GoogleMapsEvent.INFO_OPEN)
                                .subscribe(data => console.log('event opened', data));
                            this.markers.push(marker)
                        })
**Other information:**

**package.json info:**
```
{
    "name": "Custodian",
    "author": "Tixif",
    "homepage": "http://tixif.com/",
    "private": true,
    "scripts": {
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve",
        "lint": "ionic-app-scripts lint"
    },
    "dependencies": {
        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "@angular/platform-browser": "4.1.3",
        "@angular/platform-browser-dynamic": "4.1.3",
        "@ionic-native/calendar": "^4.0.0",
        "@ionic-native/camera": "^4.0.0",
        "@ionic-native/core": "^4.0.0",
        "@ionic-native/file": "^4.0.0",
        "@ionic-native/file-transfer": "^4.0.0",
        "@ionic-native/geolocation": "^4.0.0",
        "@ionic-native/google-maps": "^4.0.0",
        "@ionic-native/launch-navigator": "^4.0.0",
        "@ionic-native/location-accuracy": "^4.0.0",
        "@ionic-native/splash-screen": "^4.0.0",
        "@ionic-native/status-bar": "^4.0.0",
        "@ionic/cli-plugin-cordova": "^1.4.0",
        "@ionic/cli-plugin-ionic-angular": "^1.3.1",
        "@ionic/storage": "^2.0.1",
        "angular-calendar": "^0.18.3",
        "angular2-jwt": "^0.2.3",
        "cordova-plugin-actionsheet": "^2.3.3",
        "cordova-plugin-camera": "^2.4.1",
        "cordova-plugin-console": "1.0.7",
        "cordova-plugin-device": "1.1.6",
        "cordova-plugin-file": "^4.3.3",
        "cordova-plugin-file-transfer": "^1.6.3",
        "cordova-plugin-googlemaps": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps",
        "cordova-plugin-splashscreen": "~4.0.1",
        "cordova-plugin-statusbar": "2.2.3",
        "cordova-plugin-whitelist": "1.3.2",
        "cordova-sqlite-storage": "~2.0.3",
        "ionic-angular": "3.5.0",
        "ionic-cache": "^2.0.4",
        "ionic-image-loader": "^3.2.1",
        "ionic-plugin-keyboard": "~2.2.1",
        "ionicons": "3.0.0",
        "lodash": "^4.17.4",
        "ngx-restangular": "^1.0.11",
        "rxjs": "5.1.1",
        "sw-toolbox": "3.6.0",
        "uk.co.workingedge.phonegap.plugin.launchnavigator": "^4.0.0",
        "zone.js": "^0.8.11"
    },
    "devDependencies": {
        "@ionic/app-scripts": "2.0.0",
        "@ionic/cli-plugin-cordova": "1.4.0",
        "@ionic/cli-plugin-ionic-angular": "1.3.1",
        "codelyzer": "^3.1.2",
        "tslint": "^5.1.0",
        "typescript": "2.3.3"
    },
    "cordovaPlugins": [
        "cordova-plugin-whitelist",
        "cordova-plugin-console",
        "cordova-plugin-statusbar",
        "cordova-plugin-device",
        "ionic-plugin-keyboard",
        "cordova-plugin-splashscreen",
        "cordova-sqlite-storage",
        "cordova-plugin-calendar",
        "cordova-plugin-compat",
        {
            "locator": "https://github.com/mapsplugin/cordova-plugin-googlemaps.git",
            "id": "cordova-plugin-googlemaps"
        },
        "cordova-plugin-geolocation",
        "cordova-plugin-request-location-accuracy"
    ],
    "cordovaPlatforms": [
        {
            "platform": "android",
            "version": "",
            "locator": "android"
        }
    ],
    "description": "custodian-mobile: A Tixif project",
    "cordova": {
        "plugins": {
            "cordova-plugin-console": {},
            "cordova-plugin-device": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-whitelist": {},
            "cordova-sqlite-storage": {},
            "ionic-plugin-keyboard": {},
            "uk.co.workingedge.phonegap.plugin.launchnavigator": {},
            "cordova-plugin-file-transfer": {},
            "cordova-plugin-file": {},
            "cordova-plugin-camera": {},
            "cordova-plugin-googlemaps": {
                "API_KEY_FOR_ANDROID": "key-removed-for-showing-purposes"
            }
        }
    }
}

``````json
insert the content here
```

**Comment by JaneDawson** [comment]
Same here.
`Property 'infoClick' does not exist on type 'MarkerOptions'.`

**Comment by ihadeed** [comment]
@JaneDawson your issue is different, see https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v2.0.0/migrate-from-v1#removed-the-xxxclicked-properties

**Comment by JaneDawson** [comment]
Thanks for pointing out, @ihadeed. I didn't know that. 
Does this mean, that from version 4.0.0 on Ionic Native Google-Maps only supports v2.0 of the cordova-google-maps-plugin?

**Comment by ihadeed** [comment]
@JaneDawson yes, that was mentioned in the 4.0.0 release notes. See https://github.com/ionic-team/ionic-native/releases/tag/v4.0.0

Usually major version changes means there are some breaking changes.

**Comment by JaneDawson** [comment]
Alright - thanks for the clarification!

**Comment by ihadeed** [comment]
@wf9a5m75 do you think there's anything wrong with our wrapper that's causing this? or is this an issue with the plugin?

**Comment by wf9a5m75** [comment]
Um, it seems fine. I will check @Alberick 's code later. (I have been working on another issue).
I will take care of this.

Merge to : https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1573

**Comment by ihadeed** [comment]
Thanks @wf9a5m75 

I only tested map events in my [Ionic Native Playground app](https://github.com/zyra/ionic-native-playground), so I know that the BaseClass works well and it attaches the event listeners correctly.

**Comment by wf9a5m75** [comment]
This code works fine with  @Alberick 's project files.


```ts
  loadMap() {
    this.mapElement = document.getElementById('map');
    this.map = this.googleMaps.create(this.mapElement, this.mapOptions);

    this.map.one(GoogleMapsEvent.MAP_READY)
      .then(() => this.map.addMarker({
          title: 'BTL Marketing',
          icon: 'blue',
          animation: 'DROP',
          position: new LatLng(BTL_COORDS.lat, BTL_COORDS.lng)
        })
        .then(marker => {
          marker.on(GoogleMapsEvent.MARKER_CLICK)
            .subscribe(() => {
              alert('clicked');
            });

        }))
  }
```

![1790](https://user-images.githubusercontent.com/167831/28487806-3baf74b4-6e4e-11e7-994c-082e1707c015.gif)

**Comment by ihadeed** [comment]
Thanks @wf9a5m75

**Comment by Cdvalencia** [comment]
[this](https://github.com/Flo-D/test-google-maps-cluster/blob/master/src/pages/home/home.ts) component work.

**Comment by tsn731** [comment]
I am having this same issue as well. I am able to subscribe to all other events except MARKER_CLICK. That event never fires. 
```
"dependencies": {
        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "@angular/platform-browser": "4.1.3",
        "@angular/platform-browser-dynamic": "4.1.3",
        "@ionic-native/core": "4.3.2",
        "@ionic-native/device": "4.3.2",
        "@ionic-native/geolocation": "4.3.2",
        "@ionic-native/google-maps": "4.2.1",
        "@ionic-native/in-app-browser": "^4.1.0",
        "@ionic-native/local-notifications": "^4.1.0",
        "@ionic-native/onesignal": "^4.3.2",
        "@ionic-native/splash-screen": "4.3.2",
        "@ionic-native/status-bar": "4.3.2",
        "@ionic/app-scripts": "3.0.0",
        "@ionic/storage": "^2.0.1",
        "cordova-android": "^6.2.3",
        "cordova-custom-config": "^4.0.2",
        "cordova-ios": "^4.4.0",
        "cordova-plugin-compat": "^1.1.0",
        "cordova-plugin-console": "^1.0.5",
        "cordova-plugin-device": "^1.1.4",
        "cordova-plugin-geolocation": "^2.4.3",
        "cordova-plugin-googlemaps": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps",
        "cordova-plugin-googlemaps-sdk": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git",
        "cordova-plugin-inappbrowser": "^1.7.1",
        "cordova-plugin-mapbox": "git+https://github.com/Telerik-Verified-Plugins/Mapbox.git",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-statusbar": "^2.2.2",
        "cordova-plugin-whitelist": "^1.3.1",
        "cordova-sqlite-storage": "^2.0.4",
        "de.appplant.cordova.plugin.local-notification": "^0.8.5",
        "ionic-angular": "3.5.3",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "leaflet": "^1.1.0",
        "moment": "^2.18.1",
        "onesignal-cordova-plugin": "^2.2.2",
        "rxjs": "5.4.0",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.12"
    },
```
I basically copied @wf9a5m75 's sample from Jul21'st in this thread, or the ionic sample app but none of them worked (thouh they are not that different).

**Comment by wf9a5m75** [comment]
`"@ionic-native/google-maps": "4.2.1"` is too old.

**Comment by tsn731** [comment]
good catch `"@ionic-native/google-maps": "4.3.2",` installed, but same result. 
All other events like map click, map drag start/end are fired, but no marker events.

**Comment by wf9a5m75** [comment]
Make sure the version number of `@ionic-native/google-maps` plugin you reinstalled is really 4.3.2.
Check the package.json file in the node_modules folder.

Even if you can not solve the problem by yourself, please share your project files (not only your code) on github. I will check it.

**Comment by tsn731** [comment]
Yeah its really 4.3.2. 
I have created a fresh project with all latest versions. Please check my repo. https://github.com/tsn731/ionic-native-maps

**Comment by wf9a5m75** [comment]
I just built and run your project files, and works perfectly.
(Since you don't specify the `draggable: true`, the marker is not able to drag)
https://github.com/tsn731/ionic-native-maps/blob/e7736a0ae604e3c0451f4387540552f265ca58ac/src/pages/home/home.ts#L56-L61

![1790](https://user-images.githubusercontent.com/167831/32138982-5f3b80f2-bbf2-11e7-9a7a-8862d7c35bde.gif)

**Comment by tsn731** [comment]
That is weird. I wonder if its environmental. Would you mind sharing your Android version? Mine is Android 4.4 (I know, right?) I am going to try this on a newer version and see. 
But thanks for trying it out.

**Comment by wf9a5m75** [comment]
I confirmed the APK file I built from your project files run on my Android 4.4.4 and Android 8.0.

**Comment by tsn731** [comment]
I can confirm that the marker events are working on my 8.0.

**Comment by phoenixsachin** [comment]
marker.on(GoogleMapsEvent.MARKER_CLICK).subscribe(() => {
      alert('clicked');
    });

TypeError: marker.on is not a function
 what is this issue. please help
