### ISSUE TITLE
@ionic-native/printer not working

### ISSUE THREAD

**Issue by seetadev** [ionic-team/ionic-native#1400]
I have added the plugin as explained in the documentation. [Printer plugin](https://ionicframework.com/docs/native/printer/) . Also, added the `Printer` provider in `app.module.ts`
Now when I call the printer plugin, it does not open the print preview window. The code is as follows:
```javasacript
this.printer.isAvailable().then(function(){
	      this.printer.print(content, options).then(function(){
	          console.log("Done!");
	      }, function(error){
	          console.log("Error while printing!");
	      });
	    }, function(error){
	          console.log("Failed.")
	    });
```

**Comment by lynzz** [comment]
```
this.printer.isAvailable().then((onsuccess: any) => {

        let options: PrintOptions = {
            name: 'MyDocument',
            printerId: 'printer007',
            duplex: true,
            landscape: true,
            grayscale: true
        };
       this.printer.print('<h1>aaa</h1>',options).then((value: any) => {
                console.log('value:', value);
            }, (error) => {
                console.log('error:', error);
            });

    }, (err) => {
        console.log('err:', err)
    });
```
[
![printer](https://cloud.githubusercontent.com/assets/348917/26135661/8ffd1186-3ae9-11e7-8fff-2b8d69f4f48f.jpg)

**Comment by arcadius** [comment]
Same here, using ionic-native version ```3.10.3```

On the Brwser platform, I am getting error when ```isAvaliable()``` is being called:

```
TypeError: Printer_1.getPlugin(...).check is not a function
    at index.js:68
    at new t (polyfills.js:3)
    at Printer.check (index.js:66)
    at Printer.value [as check] (decorators.js:49)
    at Printer.isAvailable (index.js:58)
    at PrintService.<anonymous> (PrintService.ts:39)
```
My code is very similar to what @lynzz posted above

**Comment by Darkarmour** [comment]
I am also facing the same issue. . If anyone find a breakthrough for this TypeError issue . .Let us Know .Thanks in adavance

**Comment by perscrew** [comment]
Hi everybody, same issue here too : 

```
TypeError: Printer_1.getPlugin(...).check is not a function
    at index.js:68
    at new t (polyfills.js:3)
    at Printer.check (index.js:66)
    at Printer.value [as check] (decorators.js:49)
    at Printer.isAvailable (index.js:58)
    at PrintService.<anonymous> (PrintService.ts:39)
```

**Comment by SimplyComplexable** [comment]
Hey everyone,

To fix this issue, I uninstalled the current version of the plugin (0.7.3) and installed the latest version (0.7.4). I did so using the following commands:
`ionic plugin rm de.appplant.cordova.plugin.printer
ionic plugin add https://github.com/katzer/cordova-plugin-printer.git`
After doing this commands are working as expected. According the the repo, 0.7.4 is meant to correct these issues on Android N+, not sure why it hasn't been officially released yet.

**Comment by jollysean** [comment]
Somehow the command was not able to install on windows 8 from gut. So did, 
cordova plugin add https://github.com/katzer/cordova-plugin-printer.git
and 
cordova build.
It worked.

**Comment by Omagano** [comment]
Hey Everyone

would this work on android 4.2.2?

**Comment by water-melon91** [comment]
this error fix ???

**Comment by water-melon91** [comment]
Same here, using ionic-native version 3.20

**Comment by danielsogl** [comment]
Hey, I added the correct npm package `cordova-plugin-printer`.
If you still get errors like that, it is not a problem with the ionic-native wrapper.

**Comment by Kev1n337** [comment]
You can specify an network URL in PrintOptions as it is shown in the docs ('printer007'), but it could lead to the "Printing to null" error on iOS.

```
this.printer.print(content, {printerId: 'networkURL'})
```

When you add an invalid value there, you'll get the described error "printing to "(null)". 
When you don't specify a value at all, you'll be redirected to the default AirPrint view, where you can search for printers. (Same for android).

You can find more options to add in the official [docs](https://ionicframework.com/docs/native/printer/)
