### ISSUE TITLE
'InAppPurchase2' refers to a value, but is being used as a type here.

### ISSUE THREAD

**Issue by jbalducc** [ionic-team/ionic-native#3392]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request

**Current behavior:**
After updating @ionic/angular from 4.11.10 to 5.0.7 and @ionic-native/in-app-purchase-2 from  5.20.0 to 5.24.0, when I execute the command ionic build --prod I have the following error:
```
ERROR in src/app/services/in-app-purchase.service.ts:125:20 - error TS2749: 'InAppPurchase2' refers to a value, but is being used as a type here.
private store: InAppPurchase2 
```

**Expected behavior:**
The error appeared after those updates, it is assumed that when executing this command it should compile.

**Steps to reproduce:**
Update to the latest version of this library
Run ionic build --prod command

**Related code:**
**in-app-purchase.service.ts file**
```
import {Injectable} from '@angular/core';
import {Platform} from '@ionic/angular';
import {InAppPurchase2} from "@ionic-native/in-app-purchase-2/ngx";

@Injectable()
export class InAppPurchaseService {

  constructor(
    private store: InAppPurchase2,
    public platform: Platform)
  {
  }
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   Ionic CLI                     : 6.6.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/Users/jerome/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v12.12.0 (/usr/local/Cellar/node/12.12.0/bin/node)
   npm               : 6.14.4
   OS                : macOS Catalina
   Xcode             : Xcode 11.4.1 Build version 11E503a```

**Comment by martrix78** [comment]
I now got the same problem

**Comment by ElCarsten** [comment]
+1

**Comment by hermandinho** [comment]
Any solutions?

**Comment by antal-horvath** [comment]
I'm not sure I had the exact same problem as you have, yet, I was also encountering the error
`ERROR in src/app/services/in-app-purchase.service.ts:125:20 - error TS2749: 'InAppPurchase2' refers to a value, but is being used as a type here.
private store: InAppPurchase2 `

In my case, I imported
`import {InAppPurchase2} from "@ionic-native/in-app-purchase-2/ngx";`
in the service file `in-app-purchase.service.ts`, but mistakenly imported
`import { InAppPurchase2 } from "@ionic-native/in-app-purchase-2";`
in the `app.module.ts`.

Adjusting the second import also to `@ionic-native/in-app-purchase-2/ngx` solved the problem for me.

**Comment by ska-lbit** [comment]
@antal-horvath It is resolved my issue
